### ISSUE TITLE
cannot hide instructions

### ISSUE THREAD

**Issue by rolandoldengarm** [mapbox/mapbox-gl-directions#101]
As per the instructions, I want to hide the inputs and instructions:

````
 this.directions = new MapboxDirections({
        unit: 'metric', 
        profile: 'walking',
        controls: {
          inputs: false,
          instructions: false
        }
      });
````
However, the instructions are not hidden. 

An if statement is missing here: https://github.com/mapbox/mapbox-gl-directions/blob/master/src/directions.js#L54

**Comment by mapsam** [comment]
Hi @rolandoldengarm - you're correct. This was my fault in the recent 3.x updates. I'll try and get a fix out soon!

**Comment by mapsam** [comment]
`3.0.3` has been released - CDN will be up after this is merged in gl-js: https://github.com/mapbox/mapbox-gl-js/pull/3754

**Comment by mapsam** [comment]
@rolandoldengarm `3.0.3` is released and should fix this!

**Comment by mckb** [comment]
Is it possible to hide/show the instructions <div> after the directions control has been added to the map?
I've tried to change the instructions value at run-time using the .actions.setOptions( options ) which does change the instructions value, but this is not visually reflected on the map.

**Comment by mckb** [comment]
Btw, I solved the dynamic hide/show of instructions with the following;

```
let instructions = document.getElementsByClassName("directions-control-instructions")[0];
instructions.style.visibility = hide ? "hidden" : "";
```

**Comment by mckb** [comment]
The following seems a better alternative;

```
let instructions = document.getElementsByClassName("directions-control-instructions");
instructions[0].hidden = hide;
```
