### ISSUE TITLE
Multiple routes on a map?

### ISSUE THREAD

**Issue by rolandoldengarm** [mapbox/mapbox-gl-directions#102]
I would like to plot multiple routes on a map. However, this is not working, I get "No route found" twice in the directions panel.

I can't find any documentation about this. The documentation states: 

> removeRoutes
> Removes all routes and waypoints from the map.
> Returns MapboxDirections this;

So the word "All" makes me believe this should be possible?

I am creating a new MapboxDirections object for each route, and add that as a control to my map.

**Comment by mapsam** [comment]
Hi @rolandoldengarm - are you looking to plot multiple routes on a map from a single controller? Currently the plugin is built to update the route data every time a new route is generated. The "all" refers to whether a calculated route includes an _alternative_ route, but I can see how that may be misleading.

**Comment by rolandoldengarm** [comment]
Yes, I want to plot multiple routes at once. E.g. Auckland -> Wellington and Christchurch -> Milford Sound (I am NZ based).
I'm using the directions API now and plotting the route manually, which works fine. So not using the Mapbox GL Directions plugin anymore.

**Comment by mapsam** [comment]
Glad to hear you're using the API directly. Adding the option for multiple routes would change this plugin architecture dramatically, so building something separate sounds like the best alternative. Closing this!
