### ISSUE TITLE
Website license " BSD licensed."  - Github repo is : "ISC"

### ISSUE THREAD

**Issue by ImreSamu** [mapbox/mapbox-gl-directions#108]
According the website documentation: https://www.mapbox.com/mapbox-gl-js/plugins/
this plugin is " BSD licensed."  -  but the Github  repo is ISC .  
( I hope this is  a good place to report this )

![image](https://cloud.githubusercontent.com/assets/2217320/21284313/65751cc6-c418-11e6-9a6f-f4cc4583d66e.png)

Github Screenshot:  
![image](https://cloud.githubusercontent.com/assets/2217320/21284329/a2a3fb1c-c418-11e6-81eb-5d9d655ef2e5.png)

**Comment by ImreSamu** [comment]
probably the similar problem with: 
*  https://github.com/mapbox/mapbox-gl-draw/issues/567
*  https://github.com/mapbox/mapbox-gl-geocoder  ( ISC vs BSD )  (  but  I don't created an issue  )

**Comment by mapsam** [comment]
Hey @ImreSamu thanks for reporting! I'll get back to you with which license is the correct one.

**Comment by mapsam** [comment]
PR here: https://github.com/mapbox/mapbox-gl-js/pull/4230
