### ISSUE TITLE
mapbox-gl-directions hits api.mapbox.com for geocoder

### ISSUE THREAD

**Issue by willwhite** [mapbox/mapbox-gl-directions#147]
mapbox-gl-directions hardcodes api.mapbox.com for the geocoder

https://github.com/mapbox/mapbox-gl-directions/blob/e962b7e57b3e766e200ff20f79092db35850a261/src/controls/geocoder.js#L10

This should respect the `api` option.

**Comment by lbud** [comment]
Related: `api` option is undocumented https://github.com/mapbox/mapbox-gl-directions/issues/149
