### ISSUE TITLE
unable to hide profile ui (Traffic, Driving, Walking, Cycling)

### ISSUE THREAD

**Issue by kartikgreen** [mapbox/mapbox-gl-directions#148]
I do not find options to hide / remove profile ui(Traffic, Driving, Walking, Cycling) from the mapbox api. Is there any options available?

screenshot of profile ui. This is the section, I need to hide,
![profile-ui-mapbox](https://user-images.githubusercontent.com/11583535/30277191-aa0a141a-9724-11e7-8185-70c2dd36d492.png)

**Comment by lbud** [comment]
@kartikgreen you can hide the profile UI with the `controls.profileSwitcher` parameter, as documented [here](https://github.com/mapbox/mapbox-gl-directions/blob/master/API.md#mapboxdirections).

**Comment by kartikgreen** [comment]
Thanks for this option. Btw when did you add this new options?
