### ISSUE TITLE
Error on NPM bundle ` Cannot assign to read only property 'exports' of object '[object Object]'`

### ISSUE THREAD

**Issue by RyanAquino** [mapbox/mapbox-gl-directions#158]
when i installed mapbox-gl-directions using NPM. and imported it in my project it shows me this error `Cannot assign to read only property 'exports' of object '[object Object]'`. i think its a bug, when i also tried installing it using `npm install --save @mapbox/mapbox-gl-directions , it shows  an npm warn npm WARN @mapbox/mapbox-gl-directions@3.1.2 requires a peer of mapbox-gl@^0.27.0 || ^0.28.0 but none is installed. You must install peer dependencies yourself.` but looking in my package.json i currently installed mapbox-gl@^0.42.2.

**Comment by funwithtriangles** [comment]
Just documenting a definitive solution for others. If you're seeing this in the browser console:
```
Cannot assign to read only property 'exports' of object
```
 You need to add `dist/mapbox-gl-directions` to the end of your import.

```javascript
import MapboxDirections from '@mapbox/mapbox-gl-directions/dist/mapbox-gl-directions'
import '@mapbox/mapbox-gl-directions/dist/mapbox-gl-directions.css'
``` 

See https://github.com/mapbox/mapbox-gl-directions/issues/91
