### ISSUE TITLE
Provide new release - release used on GL JS example page is not matching the docs

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-directions#175]
Coming from https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-directions/ to this repository it took me some time to realise that `options.controls.profileSwitcher` is [documented](https://github.com/mapbox/mapbox-gl-directions/blob/master/API.md) but not available in the used release and there is a need to build the plugin from master to be able to use it.

The example uses currently `v.3.1.1` but also in the latest release `v.3.1.2`  `options.controls.profileSwitcher` is not available. 

However, https://github.com/mapbox/mapbox-gl-js/pull/6577 is for updating the version number on the GL JS example page.

**Edit**: GL JS example page uses now `v.3.1.2`

**Comment by morgant** [comment]
I too am hoping for a new release in the near future. I’ve got a deployed product waiting on the fixes to how styles are applied which provided in PR #168 (don't add duplicate layers when custom styles are provided).

**Comment by pathmapper** [comment]
Thanks @tristen for providing the new release!

**Comment by pathmapper** [comment]
Wait until https://github.com/mapbox/mapbox-gl-js/pull/6583 is merged before closing here.
