### ISSUE TITLE
Instructions are only shown for first leg if a route contains a waypoint

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-directions#181]
mapbox-gl-directions: v3.1.3
mapbox-gl-js: v0.45.0

![instructions_issue](https://user-images.githubusercontent.com/20856381/39864750-ef9ee85a-544a-11e8-87ad-63171b2e6adb.gif)

**Example:**
http://jsbin.com/ripozotobu/edit?html,output

Additionally the Waypoint is named incorrectly with "B":

![auswahl_295](https://user-images.githubusercontent.com/20856381/39864940-90148308-544b-11e8-9a84-1c6387e9adba.png)

**Comment by underoot** [comment]
Was fixed in #310
