### ISSUE TITLE
Unable to unsubscribe from event listeners

### ISSUE THREAD

**Issue by hutch120** [mapbox/mapbox-gl-directions#193]
Hi All,

I've just spent quite a while tracking down an issue that results in multiple triggering of the `on('xxxx')` functions. 

I have a react application that moves between pages, and loads/unloads components as it should. But, when I unload this module, it maintains the listener state, despite calling removeControl.

Essentially the issue (other than annoyance of multiple callbacks) is that eventually you will hit the maxListeners limit of 10 if you call the `on` handlers. E.g. on('route') because there is no way to unregister listeners, not even by using removeControl.

I've got a workaround in my code that sets a static variable, and checks that before registering the listener, but `feelsbadman`.

I think there are two things that could resolve this.

1) Remove listeners on removeControl

```
{
    key: 'onRemove',
    value: function onRemove(map) {
      this._events[type] = null; // <<====== ADD THIS LINE
```

and/or 

2) Add an `un` function to remove a listener. A bit harder..

```
{
    key: 'un',
    value: function on(type, fn) {
      this.actions.eventUnSubscribe(type, fn);
      return this;
}
```

```
function eventUnSubscribe(type, fn) {
  return function (dispatch, getState) {
    var _getState8 = getState(),
        events = _getState8.events;

    events[type] = events[type] || [];
    // >>>>> FIND AND REMOVE THE EVENT <<<<<
    return {
      type: types.EVENTS,
      events: events
    };
  };
}
```

**Comment by patrix** [comment]
I had the same problem, then I choose the second option.

The issue **#40** have a [commit ](https://github.com/mapbox/mapbox-gl-directions/commit/657c0dd377e66714f6b9c218fbf527727a757d9c#diff-030dc034143435907e8abd6287b18045) related that implements the off method like the your _un_ function.

**Comment by hutch120** [comment]
@patrix Thanks for referencing that code. I'll close this issue. For reference, my workaround in React looks something like this:

```
class MapComponent extends React.Component {
  static routeListenerAdded

  componentDidMount () {
    this.mbControlDirections = new window.MapboxDirections({ ... })
    if (!MapComponent.routeListenerAdded) {
      MapComponent.routeListenerAdded = true
      this.mbControlDirections.on('route', evt => { ... })
    }
  }

  componentWillUnmount () {
    if (this.mbControlDirections) {
      this.mbMap.removeControl(this.mbControlDirections)
    }
  }
}
```

**Comment by neeleshbisht99** [comment]
Can you please elaborate the second method a bit more ?

**Comment by hutch120** [comment]
@neeleshbisht99 patrix coded it... not sure how much clearer it can be than that... https://github.com/mapbox/mapbox-gl-directions/pull/194

**Comment by neeleshbisht99** [comment]
@hutch120 I got it , thanks

**Comment by douglasg14b** [comment]
It's still ambiguous, it doesn't seem to comment on how it guarantees function matches. For instance, does it unsubscribe:

```js
 map.on('zoom' () => handleZoom());

map.off('zoom' () => handleZoom());
```

My understanding is that this might not actually work. If not, then that's a gotcha that isn't made clear.
