### ISSUE TITLE
unable to send more than one waypoint getting response status 422 "message:Too many coordinates; maximum number of coordinates is 3"

### ISSUE THREAD

**Issue by awinashjaiswal** [mapbox/mapbox-gl-directions#210]
while making direction api request getting error as more than 3 coordinate  cannot be passed ;
https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-155.088899,19.722942;-155.08565,19.72472;-155.084661,19.723701;-155.083569,19.723139;-155.079557,19.722262;-155.074227,19.721938;-155.069939,19.722545;-155.07007,19.711726.json?geometries=polyline&steps=true&overview=full&access_token=**my-token**
Replace **my-token** with your token while testing the link

**Comment by gerben-van-eck** [comment]
The driving-traffic profile has a limit of 3 coordinates. If you use the 'driving' profile you get a limit of 25, the only difference is you won't get traffic info.
This is documented here: https://docs.mapbox.com/api/navigation/#directions

**Comment by geografa** [comment]
Closing here since this is documented (thanks @gerben-van-eck ). Feel free to create a new issue for alternative error handling.
