### ISSUE TITLE
Can't exclude ferries, tolls or motorways on the route

### ISSUE THREAD

**Issue by bbantsadze** [mapbox/mapbox-gl-directions#232]
I'm using the latest version: `4.0.2` and passing `exclude` parameter like this:
```
new MapboxDirections({
      accessToken: this.accessToken,
      unit: 'metric',
      profile: 'mapbox/driving',
      flyTo: false,
      styles,
      controls: {
        inputs: false,
        instructions: false,
        profileSwitcher: false
      },
      exclude: 'ferry'
    });
```

But it doesn't exclude ferries. What am i doing wrong?

**Comment by geografa** [comment]
@bbantsadze could you please add the API request here as well? You can use the API Playground to generate the request URL: https://www.mapbox.com/api-playground/#/directions?_k=nhxwpq.

**Comment by bbantsadze** [comment]
> @bbantsadze could you please add the API request here as well? You can use the API Playground to generate the request URL: https://www.mapbox.com/api-playground/#/directions?_k=nhxwpq.

```https://api.mapbox.com/directions/v5/mapbox/driving/-94.775876%2C29.364116%3B-94.772278%2C29.325585.json?geometries=polyline&steps=true&overview=full&language=en&access_token=```

**Comment by geografa** [comment]
@bbantsadze thanks for confirming this. 

![image](https://user-images.githubusercontent.com/134753/71029274-e8858f00-20c3-11ea-97d5-c8b7c17572b9.png)

Looks like the exclude is working, however, the exclude parameter is not included in the plugin just yet (https://github.com/mapbox/mapbox-gl-directions/blob/master/src/directions.js#L19). If you'd like to contribute, you can create a pull request to have this added. In the meantime, you can still use the API directly and add specific parameters or use the [Mapbox JavaScript SDK](https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/services.md#getdirections).

**Comment by bbantsadze** [comment]
Thanks for response. I checked and it worked, so created a pull request.

**Comment by bbantsadze** [comment]
Merge was completed. Thanks.

**Comment by Lazza** [comment]
There seems to be no way to toggle this option at runtime, am I missing something obvious?
