### ISSUE TITLE
Directions treats way name changes as intersections

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox-gl-directions#37]
_This is very likely a ticket for the directions API or data team, but if those are internal this may be the best bet; please direct me if this should be posted elsewhere_

<img width="1255" alt="screenshot 2015-12-11 12 12 03" src="https://cloud.githubusercontent.com/assets/735463/11750343/cdc6a6ce-a000-11e5-84b5-37279c10ed1e.png">

In certain sections of US Interstate highway navigation, the directions plugin is offering guidance at every exit and subtle change of road name. I'm not familiar with how the underlying data came to be structured this way, but the navigation algorithm should be able to recognize consistency between segments of the same limited-access highway.

**Comment by tristen** [comment]
cc @TheMarex

**Comment by TheMarex** [comment]
@wboykinm Thanks for reporting this. For future reference we usually keep these issues in https://github.com/Project-OSRM/osrm-backend which is our routing engine in the background.

This is a known issue, and we are going to re-write our turn instruction code for the next release. Do you have a link to the specific route? The problem at hand is more a data problem (someone didn't add the street name to all ways in OSM). Should be straight forward to fix.

**Comment by wboykinm** [comment]
@TheMarex [This one](http://wboykinm.github.io/midpoint/nav/?start=-73.2125382,44.4521363&end=-72.57511549559159,44.26240369447109) seems to have a lot of that going on. It totally looks like a data problem, but one that could at least be smoothed over with some routing logic. Thanks!
