### ISSUE TITLE
Autocomplete needs backspace to autocomplete

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapbox-gl-directions#42]
I need to hit the backspace to get suggestions in the drop down box.

![typeahead](https://cloud.githubusercontent.com/assets/98233/11810697/f30ca1d8-a355-11e5-81bb-26d1d78a1c6e.gif)

**Comment by tristen** [comment]
Hmm yeah - something is off that doesn't seem to effect the [geocoder](https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/).

**Comment by tristen** [comment]
Looks like there's some queueing issue between the dispatcher and input query. What should be issued is in the wrong order:

<img width="413" alt="screen shot 2015-12-15 at 9 06 52 am" src="https://cloud.githubusercontent.com/assets/61150/11812708/68ee1846-a30b-11e5-8533-ac0ac98d3c28.png">

**Comment by tristen** [comment]
Closing. There are outstanding performance issues around requests that will be addressed in other tickets and in the meantime:

- Requests are not run if there are < 2 characters in the input element.
- debouncing the `keydown` event

Improve this issue.
