### ISSUE TITLE
Plugin not taking the clicked position

### ISSUE THREAD

**Issue by srividyacb** [mapbox/mapbox-gl-directions#53]
When clicked on the map the marker is not appearing at the clicked place but displaying in another place. 

**To recreate the same:**
- Zoom in to India.
- Click on one of the major roads near Pune.

**What I expect** :- Marker/circle to appear on the clicked place.

**What I see** :- Marker appearing away from the clicked place and geocoding to Maharashtra.

![ani1](https://cloud.githubusercontent.com/assets/3423533/13519425/ee4cd398-e1fd-11e5-9ce4-808ec9bfad30.gif)

**Comment by planemad** [comment]
Something geocoding related? 
cc @tristen

**Comment by geografa** [comment]
Seeing the same in areas in Malaysia:
http://bl.ocks.org/geografa/f16696a0d5fd7586404d

**Comment by reezangel** [comment]
Thanks rafa for pointing out the problem

**Comment by tristen** [comment]
Ahh this issue was fixed in https://github.com/mapbox/mapbox-gl-directions/pull/47. I just need to release a new version. I'd like to care of a backlog of issues before that happens. I'll leave this open until that happens.

**Comment by reezangel** [comment]
Hi Tristen, May I know when will this v1.1.0 be made available?

**Comment by tristen** [comment]
Apologies on the delay here - a v2.0.0 release was made that addressed this issue!

**Comment by reezangel** [comment]
Thanks for the efforts. Works well .
