### ISSUE TITLE
broken with mapbox-gl-js 0.16 due to featuresAt breaking change

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-directions#56]
`src/directions.js` still uses map.featuresAt which is broken due to https://github.com/mapbox/mapbox-gl-js/pull/2224 with mapbox-gl-js 0.16.

/cc @lyzidiamond This is also affecting the example at https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-directions/

**Comment by tristen** [comment]
Thanks for the heads up! This will be fixed in the very next release.
