### ISSUE TITLE
Point main in package.json to dist/mapbox-gl-directions.js

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-directions#63]
Babel shouldn't be required in order for clients to use this via Browserify. cc @tadjohnston

**Comment by tb0yd** [comment]
Is pointing to `dist/` the best solution here? It makes it difficult to debug when minified code is linked in development mode. I am using Webpack, not Browserify.

Is there a fix that would make this project forward-compatible with Babel 6?

**Comment by tristen** [comment]
atm this fixes a bug. ES6 code should be transpiled to ES5 (which is widely supported) to support any module loader. I'm happy to un-minify what's in `dist` though.
