### ISSUE TITLE
Dragging markers around causes markers to jump around erratically

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-directions#67]
from https://github.com/mapbox/mapbox-gl-js/issues/2545

> The example at https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-directions/ is not working correctly with Chrome on Mac.

> Dragging markers around causes markers to jump around erratically.

cc @emiltin @tristen

**Comment by tristen** [comment]
Yeah ... pretty sure this is related to https://github.com/mapbox/mapbox-gl-directions/issues/36
