### ISSUE TITLE
allow custom osrm servers

### ISSUE THREAD

**Issue by emiltin** [mapbox/mapbox-gl-directions#68]
looking at the api doc i cannot see any option to use a custom osrm server? we're running our own custom bike profiles that on our own server

**Comment by rahimramezanian** [comment]
Hi.
Is it possible to use local osrm server for routing? 
I am looking for something like, add
`api: 'localhost:5000/route/v1/'`
instead of 
`api: 'https://api.mapbox.com/directions/v5/'`
in `initialState` object in _**mapbox-gl-directions.js**_. 
Thanks.

**Comment by willwhite** [comment]
This is supported now by setting `api`, `profile`, and (optionally) `compile` to provide a custom osrm-text-instructions compile function.
