### ISSUE TITLE
Draw route without using the directions control

### ISSUE THREAD

**Issue by johnnyluu** [mapbox/mapbox-gl-directions#70]
Hey guys,

I'm trying to implement directions without using the default interface and the clicking on map to set origin and destination because we need a more restricted user experience. I'm able to do the api call and get the data back, but I don't have any clue on how to draw that polyline. The geometry data that's returned is like ""v~gis@goo}bHg@rIoFr{@cGv~@rfCbVvy@jHrv@vGzc@rDvQnAzw@jHnAwQ", and I've no ide what it means. Is it supposed to draw the lines automatically but I didn't set things up properly? If not, how do I draw the route on the map the way the plugin draws when the directions controls is added to the map?

Thank you!

**Comment by andrewharvey** [comment]
... addressed at https://github.com/mapbox/mapbox-gl-js/issues/2646
