### ISSUE TITLE
Autocomplete results don't update when a user types very quickly

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-directions#71]
ref https://github.com/mapbox/mapbox-gl-geocoder/issues/42

**Comment by tristen** [comment]
This is now upstream in https://github.com/mapbox/mapbox-gl-geocoder/issues/42

**Comment by pathmapper** [comment]
Upstream fix https://github.com/tristen/suggestions/pull/12 is available since `suggestions v1.3.1`. 

Would updating the [dependency](https://github.com/mapbox/mapbox-gl-directions/blob/master/package.json#L70) fix this issue here?

**Comment by tristen** [comment]
@pathmapper it would yep! Added a PR to resolve this.

**Comment by pathmapper** [comment]
Thanks!
