### ISSUE TITLE
Obtaining the OSM way_id for each step in the route.

### ISSUE THREAD

**Issue by bomanimc** [mapbox/mapbox-gl-directions#74]
Is there a way to get the OSM way_id for each step in the route? These IDs for ways are commonly used in OSM, and are helpful in referencing other OSM data that is associated the components of the routes returned in the directions.

**Comment by tmcw** [comment]
Hi Bomani,

This isn't something that we currently return from the Directions API, but we have changes in development to include OSM IDs in the [Map Matching Endpoint](https://www.mapbox.com/api-documentation/#retrieve-a-match).

- Tom
