### ISSUE TITLE
Dynamically updating styles for directions

### ISSUE THREAD

**Issue by bomanimc** [mapbox/mapbox-gl-directions#78]
Is it possible to change a style outside of the initialization of the directions? For example, if one were to try and change the color of the route line after initialization.

**Comment by bomanimc** [comment]
I found that I could do something like this after the directions have been applied to the map to change the coloring: 

`map.addLayer({
                  'id': 'directions-route-line',
                  'type': 'line',
                  'source': 'directions',
                  'layout': {
                    'line-cap': 'round',
                    'line-join': 'round'
                  },
                  'paint': {
                    'line-color': '#00FF00',
                    'line-width': 4
                  },
                  'filter': [
                    'all',
                    ['in', '$type', 'LineString'],
                    ['in', 'route', 'selected']
                  ]
                })`

**Comment by tristen** [comment]
Yep! That's how you can do it ^
