### ISSUE TITLE
Change mapboxgl.GeoJSONSource() to map.addSource() for GL-JS v0.22

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapbox-gl-directions#82]
# Problem
[Version 0.22.0 of GL-JS](https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.22.0) deprecated the GeoJSONSource().

# Steps to reproduce
Use GL-JS v0.22.0 with gl-directions plugin v2.1

# Example with error message
* https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-directions/
![example](https://cl.ly/2h0G1P391314/download/Image%202016-08-12%20at%204.22.11%20PM.png)

# Solution
Convert all references to GeoJSONSource() to map.addSource()

**Known references**
1. https://github.com/mapbox/mapbox-gl-directions/blob/master/src/directions.js#L68

**Comment by tmcw** [comment]
Fixed in #86
