### ISSUE TITLE
Support for usage with Webpack

### ISSUE THREAD

**Issue by DominikLevitsky** [mapbox/mapbox-gl-directions#91]

**Comment by tmcw** [comment]
@DominikLevitsky is this a bug report? If so, please provide the error that webpack currently emits when you include this package, so that we can know where to get started.

**Comment by rolandoldengarm** [comment]
I get this error:  Uncaught (in promise): TypeError: fs.readFileSync is not a function(…)

**Comment by lisatassonesimpro** [comment]
I agree. I have the same issue. I'm unable to use this plugin because I don't use browserify as the bundler . I'm using Ionic.

**Comment by lisatassonesimpro** [comment]
@rolandoldengarm I forked the repo and added a dist folder with the bundled plugin code ([https://github.com/lisatassonesimpro/mapbox-gl-directions/tree/distribution-build]). I've been able to use this successfully in my ionic project using webpack.

**Comment by mapsam** [comment]
@rolandoldengarm @lisatassonesimpro I believe the dist folder is not included to prevent unnecessary merge conflicts for minified files. That being said, we can create an `.npmignore` file which _unignores_ the dist file coming from `.gitignore`, and should ship with a publish.

**Comment by lisatassonesimpro** [comment]
Thanks @mapsam, much appreciated. It's really just to save us the time of having to build it ourselves so we can get up and running asap. Cheers

**Comment by anandthakker** [comment]
Done in https://github.com/mapbox/mapbox-gl-directions/pull/120 and published in 3.1.2

**Comment by mapsam** [comment]
Thanks @anandthakker!

**Comment by funwithtriangles** [comment]
Just documenting a definitive solution for others. If you're seeing this in the browser console:
```
Cannot assign to read only property 'exports' of object
```
 You need to add `dist/mapbox-gl-directions` to the end of your import.

```javascript
import MapboxDirections from '@mapbox/mapbox-gl-directions/dist/mapbox-gl-directions'
import '@mapbox/mapbox-gl-directions/dist/mapbox-gl-directions.css'
```
