### ISSUE TITLE
Use new mapboxgl Control system

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-directions#94]
https://github.com/mapbox/mapbox-gl-js/pull/3497

The new IControl interface will allow mapbox-gl-directions to remove any dependency on mapboxgl, eliminating a popular class of installation bugs. Once mapboxgl is updated, or before if you're feeling saucy, update to the new interface.

**Comment by tmcw** [comment]
cc @mollymerp @mapsam @mapbox/appbox  does anyone want to potentially hop on this one? And does anyone want to join the general effort of keeping our constellation of mapbox-gl plugins up to date and stable?

**Comment by davidtheclark** [comment]
> does anyone want to join the general effort of keeping our constellation of mapbox-gl plugins up to date and stable

@tmcw Do you think it makes sense to delegate maintainers for particular plugins? I can take one.

**Comment by tmcw** [comment]
I think that's a capital idea.

I think GitHub has some rumored system where each project has the 'responsible party' or something. Right now we have three plugins:

* mapbox-gl-geocoder (I just refactored this one)
* mapbox-gl-directions (this one)
* mapbox-gl-draw

**Comment by mapsam** [comment]
> capital idea

Indeed. Happy to jump on one of these @tmcw. gl-draw is interesting to me, though I know nothing about it.

**Comment by davidtheclark** [comment]
@tmcw I'm happy to take on mapbox-gl-directions, but might not be able to do so right away. How urgent should I consider this?

**Comment by tmcw** [comment]
It's unfortunately rather urgent. If you don't have bandwidth for this immediately, I can try to do a super minimal refactor that just gets it working again and leave the more interesting bits as for the future.

**Comment by davidtheclark** [comment]
@tmcw My top priority right now is finishing up the style form refactor; so, yeah, if you'd like to jump in sooner, that would great. I'll start familiarizing myself with this plugin after that.

**Comment by tmcw** [comment]
@mapsam want to grab this?

So the gist is:

* Controls should no longer rely on mapboxgl as a global or require. Luckily this module only does in two places afaik - grabbing an access token and wrapping coordinates.
* Instead of addTo and remove, which basically treat the control as the one in charge, GL JS is in charge with the `.addControl` and `.removeControl` methods and the control needs to implement onAdd and onRemove in order to hook into these
* Instead of the control adding itself to the DOM, it returns an element and GL JS does that in addControl. This also means they no longer use a `position` property as input: that's handled in addControl.

**Comment by mapsam** [comment]
@tmcw making progress here, but stuck on one thing. The access token makes its way into the directions api calls, but I'm not sure how to give the access token to the geocoder. Any clues?

**Comment by mapsam** [comment]
I'm also unable to get this working in `master` - is there an old screenshot of what the controls should look like? Everything is a bit wonky right now and I'm not 💯  sure where everything is expected to be.

**Comment by tmcw** [comment]
In the new Geocoder control, you provide an accesstoken to the control. Slightly less convenient but  more direct than grabbing from mapboxgl.accessToken as a global.
